services:
  darthvader:
    build: dnsserver
    hostname: dnsserver
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./dnsserver/conf/primario/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/primario/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/primario/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/conf/primario/db.20.168.192:/etc/bind/db.20.168.192
  darthsidious:
    build: dnsserver
    hostname: dnsserver2
    networks:
      rededns:
          ipv4_address: 192.168.20.11
    volumes:
      - ./dnsserver/conf/secundario/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/secundario/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/secundario/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/conf/secundario/db.20.168.192:/etc/bind/db.20.168.192
  eq1:
    build: debian
    hostname: eq1
    networks:
      rededns:
          ipv4_address: 192.168.20.100
    dns:
      - 192.168.20.10
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

